name: CI / CD
on:
  push:
  workflow_dispatch:
jobs:
  Build-and-publish:
    name: Build-and-publish
    runs-on: ubuntu-latest
    container: mono:6.8.0.96
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build and test
        run: |
            ./build.sh

      - name: Package
        run: |
            ./package.sh

      - name: Publish
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
            nuget push *.nupkg -ApiKey ${{ secrets.CHOCO_KEY }} -Source https://push.chocolatey.org/ -SkipDuplicate
